/* eslint-disable prettier/prettier */
export const AUTHENTICATE_LOGIN_REQUEST = 'AUTHENTICATE_LOGIN_REQUEST';
export const AUTHENTICATE_LOGOUT_REQUEST = 'AUTHENTICATE_LOGOUT_REQUEST';
export const RETRIVE_TOKEN = 'RETRIVE_TOKEN';
export const REGISTER = 'REGISTER';
