/* eslint-disable prettier/prettier */
import {StyleSheet} from 'react-native';
export default StyleSheet.create({
mainBody: {
        flex: 1,
        justifyContent: 'center',
        alignContent: 'center',
  },
  loginContainer:{
    flex: 1,
    justifyContent: 'center',
    alignContent: 'center',
  },
  SectionStyle: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderColor: '#000',
    height: 40,
    width: 315,
    borderRadius: 10,
    margin: 10,
    marginLeft: 35,
  },
  inputStyle: {
    flex: 1,
    color: '#A2A2A2',
    paddingLeft: 15,
    paddingRight: 15,
    backgroundColor: '#FFFFFF',
    borderRadius: 10,
  },
  errorTextStyle: {
    color: 'red',
    textAlign: 'center',
    fontSize: 14,
  },
  buttonStyle: {
    backgroundColor: 'rgba(69, 156, 255, 1)',
    borderWidth: 0,
    color: '#FFFFFF',
    borderColor: '#7DE24E',
    height: 50,
    alignItems: 'center',
    borderRadius: 10,
    marginLeft: 35,
    marginRight: 35,
    marginTop: 20,
    marginBottom: 25,
  },
  signInText: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 14,
    alignSelf: 'center',
  },
  forgetPassword: {
    color: '#FFFFFF',
    textAlign: 'right',
    fontSize: 12,
    alignSelf: 'flex-end',
    paddingRight: 35,
  },
  registerTextStyle: {
    color: '#FFFFFF',
    textAlign: 'center',
    fontSize: 12,
    alignSelf: 'center',
    padding: 10,
  },
  buttonTextStyle: {
    color: '#FFFFFF',
    paddingVertical: 10,
    fontSize: 16,
  },
  homeUserNameText: {
    color: '#fff',
    fontSize: 22,
    fontWeight: '800',
    marginVertical: 5,
  },
  homeView: {
    backgroundColor: '#D01E21',
    marginBottom: 80,
  },
  homeContent: {
    marginVertical: 20,
    marginHorizontal: 20,
  },
  image: {
    width: '50%',
    height: 100,
    resizeMode: 'contain',
    margin: 30,
  },
  MenuIconStyle: {
      padding: 10,
      margin: 8,
      height: 20,
      width: 20,
      resizeMode : 'contain',
      alignItems: 'center',
      color:'#A2A2A2',
  },
  center: {alignItems: 'center'},
  backImage: {
    flex: 1,
    resizeMode: 'cover',
    justifyContent: 'center',
  },
});
